Exercise 4
Arthur264/cpp_training pull request #4
Opened 2019-07-26 15:43 UTC by Arthur264

2019-07-30 08:56 UTC, rmnkrc requested changes
In general I think your design is correct. 
I noticed that you overuse shared pointers. Please remember that shared_ptr implementation is far heavier than unique_ptr ones and so you should use it only when it is really necessary.

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/main.cpp
> +                (inv.*it.second)(matches);
Please try using lambdas here - that will sure improve readability.

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/main.cpp
> +            {Student::RECORD_PREFIX, std::make_shared<StudentFactory>()},
if you don't plan to actually share the ownership of the pointer, use unique ptr

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +    inline std::string trim(std::string &str) {
const std::string& ... since you don't change the str
please revise other methods - if the std::string& is passed but not changed then const should be added

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +            return str;
what strings do you expect to go through this branch? in such cases does returning 'str' mean trimming it?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +            return std::vector<std::string>{str};
good, "return early" is a good idiom

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +    inline std::vector<std::string> split(std::string &str, const std::string &delimiter) {
hmm ... are you sure that split should 'consume' the str?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/main.cpp
> +                std::cerr << "Invalid command argument: " << e.what() << std::endl;
what about std::out_of_range thrown from std::stoi?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +            pos = str.find(delimiter);
find can actually accept the start position. if you used that you wouldn't have to erase the str.

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +std::vector<cmd::CommandParam> CommandParser::parse_expression(std::string expression) const {
this could be const string& if cmd::split didn't modify 'expression'.

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +    auto trim_condition = cmd::trim(condition);
trim already creates a copy so std::string &condition may be const std::string &condition

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +    auto value = std::stoi(vector_params[2]);
can throw two types of exceptions - you handle only one

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.h
> +namespace cmd {
in case you don't plan to use cmd namespace outside the CommandParser how about moving it to cpp and making it the unnamed namespace?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +#include "Command.h"
you included it already in CommandParser.h

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Course.cpp
> +constexpr const char Course::RECORD_PREFIX;
+1 for using consexpr

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Course.cpp
> +                                                           _teacher_id{teacher_id} {}
consider what would be a difference in terms of copies/moves if you passed const string& and then copy to _name vs passing std::string and then move to _name

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Course.h
> +//    static constexpr const  std::unordered_map<std::string, int> PROPERTIES;
if not needed, remove :)

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Course.cpp
> +Course::Course(int id, std::string name, int teacher_id) : Record(id), _name{std::move(name)},
Record(id), can that be Record{id}?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Invoker.h
> +    std::shared_ptr<Command> _command;
since _command is used locally - it should be a local variable. Additionally it is rather a small object - use local storage instead of dynamic one.

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Invoker.h
> +    typedef void(Invoker::*InvokerFunc)(const std::smatch &);
replace typedef with using

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Record.cpp
> +Record::Record(int id) : _id(id) {}
_id{id}

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Command.h
> +    using ComparisonsMap = std::map<std::string, std::function<bool(int, int)>>;
could that be unordered_map?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Invoker.cpp
> +
your methods are actually pretty uniform, do you think you could rewrite them as one template method?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/RecordFactory.h
> +    using RecordFactories = std::unordered_map<char, std::shared_ptr<IRecordFactory>>;
could you use unique instead of shared_ptr?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/RecordStorage.cpp
> +    std::cout << "Sort " << table_name << " records in RecordStorage" << std::endl;
I guess that is debug info, please remove before pushing to master

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/RecordStorage.cpp
> +    auto compare_records_id = [](const std::shared_ptr<Record> first_record,
const& -> otherwise you will cause reference counter being increased and then decreased right after. That is actually an unnecessary overhead.

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/ShowCommand.cpp
> +        if (Command::comparisons_map.end() == comparison) {
I wonder if you could check for syntactic errors earlier. At this point you execute command and such things assessing the comparison should probably be done on parsing it.

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/ShowCommand.cpp
> +record::RecordVectorPtr ShowCommand::_filter_records(record::RecordVectorPtr records) const {
why do you copy records here?

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/Student.cpp
> +Student::Student(int id, std::string name) : Record(id), Person(std::move(name)) {}
Record{id}

2019-07-30 08:56 UTC, rmnkrc commented on exercise_3/main.cpp
> +record_factory(char &record_type, const std::string &row, const record::RecordFactories &recordFactories) {
could you return unique_ptr here?

2019-07-30 12:32 UTC, Arthur264 commented on exercise_3/main.cpp
> +record_factory(char &record_type, const std::string &row, const record::RecordFactories &recordFactories) {
@rmnkrc
I use "shared_ptr" because record can`t be as "unique_ptr"
Example:
In ShowCommand I create new "filtered_record" with  "shared_ptr" for print filtered records.

2019-07-30 12:35 UTC, Arthur264 commented
@rmnkrc  
Please, when you make review click at "Files changed" because many parts of code already changed.

2019-07-30 12:48 UTC, rmnkrc commented
@Arthur264 sure, let me know when you commit anything.

2019-07-30 12:52 UTC, Arthur264 commented on exercise_3/CommandParser.cpp
> +            return str;
@rmnkrc
Trim function return string without space at the beginning and at the end.
'  foo  ' => 'foo'
If we have a case when string already without spaces, then we will have.
'foo' => 'foo'

2019-07-30 12:54 UTC, Arthur264 commented on exercise_3/main.cpp
> +                std::cerr << "Invalid command argument: " << e.what() << std::endl;
@rmnkrc 
I don't use std::stoi.
It`s "Outdate".

2019-07-30 12:55 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +            return str;
what about a string that consists of white spaces "    "?

2019-07-30 12:55 UTC, Arthur264 commented on exercise_3/CommandParser.cpp
> +std::vector<cmd::CommandParam> CommandParser::parse_expression(std::string expression) const {
fixed

2019-07-30 12:55 UTC, Arthur264 commented on exercise_3/CommandParser.cpp
> +    auto value = std::stoi(vector_params[2]);
Outdated

2019-07-30 13:04 UTC, Arthur264 commented on exercise_3/Invoker.cpp
> +
@rmnkrc 
Yeap, some of them looks like very similar.
But from another side in "update_record" I should parse "update_params", and in "show_records" no need to parse "command_params".

2019-07-30 13:04 UTC, Arthur264 commented on exercise_3/RecordStorage.cpp
> +    std::cout << "Sort " << table_name << " records in RecordStorage" << std::endl;
removed

2019-07-30 13:04 UTC, Arthur264 commented on exercise_3/RecordStorage.cpp
> +    auto compare_records_id = [](const std::shared_ptr<Record> first_record,
Outdated

2019-07-30 14:00 UTC, Arthur264 commented on exercise_3/CommandParser.h
> +namespace cmd {
@rmnkrc
I use "cmd" namespace also in Command.h and main.cpp.

2019-07-30 14:29 UTC, Arthur264 commented on exercise_3/Invoker.h
> +    std::shared_ptr<Command> _command;
@rmnkrc 
I don't know have to describe variable with Abstract Class.
Command bp = ShowCommand(); => error: cannot allocate an object of abstract type "Command"
Command *bp = new ShowCommand(); => all okay)

2019-07-30 14:35 UTC, Arthur264 commented on exercise_3/ShowCommand.cpp
> +        if (Command::comparisons_map.end() == comparison) {
Outdated

2019-07-31 07:53 UTC, Arthur264 commented on exercise_3/CommandParser.cpp
> +            return str;
@rmnkrc 
I find a new better way)

2019-07-31 07:59 UTC, Arthur264 commented
@rmnkrc 
Can you check again)

2019-07-31 12:42 UTC, rmnkrc requested changes
Almost there.

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/Command.cpp
> +                 std::vector<record::CompareParam> command_params) :
One thing to consider here. It's a bit advanced topic. Move semantics is all about saving resources by avoiding copies. 
So if you pass a vector by const& to method A, then method A calls B and pass the vector by value. Then inside moves (std::move) the value to some member you have 1 copy and then 1 move.
On the other hand if you keep passing by const& down to B and the pass the vector to member by copy then you have only 1 copy.
At this point this may seems a bit extreme but  it is still good to know. 

Other approach would be to move vector when passing it to A and then forward it as rvalue reference.

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +        int delimiter_len = delimiter.length();
const int

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +    return vector_command_params;
nice, RVO

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +    std::vector<std::string> vector_params = cmd::split(trim_condition, " ");
auto instead of std::vector<std::string> would do

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +    auto comparison_sing = vector_params[1];
sign? or sing?

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/CommandParser.cpp
> +    auto name = vector_params[0];
since you copy name, value and comparison_sing to record::CompareParam you could use const auto& here

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/Invoker.h
> +    std::unique_ptr<Command> _command;
why do you keep the command between calls to Invoker? why not make _command a local variable and not use unique_ptr at all?

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/Record.h
> +    void validation_update(const std::string &name) const;
The names for methods should be 'verbs'. validation_update says that you want to update some validation :)

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/main.cpp
> +        exit(EXIT_FAILURE);
since you use exit(EXIT_FAILURE); it would be nice to give some err to the user at this point

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/main.cpp
> +    if (infile.fail()) {
move this check before factories init. you don't need factories if the check fails

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/main.cpp
> +    auto command_match = [&command_line, &matches](const auto &it) -> bool {
I think you don't need -> bool. Auto-deduction should work here.

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/Record.h
> +    virtual bool match(const record::CompareParam &compare_param) const = 0;
match and update are acceptable in such a simple app but in real life system you would opt for separation into model and controller/edit classes. Edit would be able to do some update/match and model would only hold data.

2019-07-31 12:42 UTC, rmnkrc commented on exercise_3/commands.txt
> +SHOW EXAM WHERE CourseId = 0 && Result = 90;
I would test it using queries starting with random letters and then the correct expressions f.e.
"asdfasdfSHOW EXAM WHERE CourseId = 0 && Result = 90;"

2019-07-31 14:34 UTC, Arthur264 commented on exercise_3/CommandParser.cpp
> +    auto comparison_sing = vector_params[1];
@rmnkrc
My grammar mistake, sorry)

2019-08-01 14:39 UTC, Arthur264 commented
@rmnkrc 
I corrected all comments below)

2019-08-01 16:46 UTC, rmnkrc commented
Nice job. I think we can finish at this point.

Btw. when you start your next project in C++, please read about google test framework. That would allow you to tests along with the implementation.

2019-08-01 16:46 UTC, rmnkrc approved these changes
Good job.

2019-08-01 18:37 UTC, merged